# Menggunakan image resmi MySQL
FROM mysql:8.0

# Mengatur variabel lingkungan
ENV MYSQL_ROOT_PASSWORD alba

# Menyalin file SQL ke dalam container
COPY siswa.sql /docker-entrypoint-initdb.d/siswa.sql
